### ISSUE TITLE
Getting Error Message: Incorrect Request. [Field 'startTime' shouldn't be null.] 

### ISSUE THREAD

**Issue by gor-p-asx** [reportportal/examples-java#14]
I have checked out this sample project, And I have added relevant reportportal properties details

Tests were throwing below error stack trace.
`
01:49:27.150 [main] INFO com.epam.reportportal.service.Launch - Rerun: false
01:49:27.319 [RxComputationThreadPool-3] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Logging context completed
01:49:27.722 [rp-io-0] ERROR com.epam.reportportal.service.Launch - [23] ReportPortal execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 400
Status message: Bad Request
Error Message: Incorrect Request. [Field 'startTime' shouldn't be null.] 
Error Type: null
	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:83)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:517)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)`

Added the image below for setup and runner 
![image](https://user-images.githubusercontent.com/50089273/72491720-f834f680-386e-11ea-8fda-2397606cdf10.png)

**Comment by evjlobanova** [comment]
@gor-p-asx which version of reportportal do you use? Please send us information from your properties file

**Comment by gor-p-asx** [comment]
Report portal version - Build 4.3
Current version: Analysis Service: 4.3.0; API Service: 4.3.0; Index Service: 4.2.0; Authorization Service: 4.2.0; Service UI: 4.3.0;

**Report portal properties file -** 
rp.endpoint = http://localhost:8080
rp.uuid = d0ed256e-e775-4b7b-8006-a332513b0d51
rp.launch = superadmin_TEST_EXAMPLE
rp.project = demo1
rp.enable = true
rp.description = My awesome launch
rp.tags = TAG1;TAG2
rp.convertimage = true
rp.mode = DEFAULT
rp.skipped.issue = true
rp.batch.size.logs = 20

**Comment by gor-p-asx** [comment]
Also attaching docker-compose file for reference 

[docker-compose.txt](https://github.com/reportportal/examples-java/files/4073816/docker-compose.txt)

**Comment by HardNorth** [comment]
@gor-p-asx We updated all the examples. I've tested them personally. Could you please try again?
BTW: RP4 examples are located in this branch: [rp-4-examples](http://github.com/reportportal/examples-java/tree/rp-4-examples)

**Comment by gor-p-asx** [comment]
Hi @HardNorth  Thanks for responding on this ..

I have switched to this version of RP now 
API Service: 5.0.0-SNAPSHOT;Index Service: 5.0.5;Authorization Service: 5.0.0-RC-5;Service UI: 5.0.0-RC-6

Which example project/ branch will be best with this ? 
Test automation Project has below dependency as of now 
		<junit.version>4.12</junit.version>
                 <cucumber.java.version>2.4.0</cucumber.java.version>
		<cucumber.junit.version>2.4.0</cucumber.junit.version>
		<cucumber.core.version>2.4.0</cucumber.core.version>

**Comment by gor-p-asx** [comment]
@Yumfriez Can you please advice on this please

**Comment by DzmitryHumianiuk** [comment]
@gor-p-asx this example is formed for RPv5.

your issue triggered cause you use v5 adopted agents against v4

**Comment by HardNorth** [comment]
@gor-p-asx First of all, please update on final version of ReportPortal V5, versions you mentioned actually were deleted from docker hub and other repositories.
Second, is that you specified cucumber ver. 2 dependencies, but you are trying to execute cucumber ver. 5 examples. They're binary incompatible, please switch on to respective versions.

**Comment by HardNorth** [comment]
Looks like answered and abandoned by the requestor.
