### ISSUE TITLE
Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener

### ISSUE THREAD

**Issue by apsharma** [reportportal/examples-java#61]
**Describe the bug**
Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener. This does not seem to be a problem with `agent-java-testng: 5.0.11` and `logger-java-log4j: 5.0.3` - at least that is the last known good versions where things worked well, in our case.

ReportPortal version: `API Service: 5.6.3;Authorization Service: 5.6.3;Service UI: 5.6.0;`

For more context about how we are sending/capturing screenshots, please see snippet below. This is overriding or using the TestNG listener interface methods.
```java
    @Override
    public void onTestFailure(ITestResult testResult) {

        Object testClass = testResult.getMethod().getInstance();
        log.debug("Detected Failure in class: {} and ReportPortal Status: {}", testResult.getName(), System.getProperty("rp.enable"));

        if(testClass instanceof FluentTestNg fluentTestNg) {
            WebDriver driver = fluentTestNg.getDriver();
            String rpEnableStatus = System.getProperty("rp.enable");

            if (rpEnableStatus!=null && rpEnableStatus.equalsIgnoreCase("true")) {

                String screenshotStr = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BASE64);
                File imgFile = OutputType.FILE.convertFromBase64Png(screenshotStr);
                ReportPortal.emitLog("Failure Screenshot", "ERROR", Calendar.getInstance().getTime(),
                        imgFile);

            } else {
                log.debug("Error Screenshot in project root");
                fluentTestNg.getFluentControl().takeScreenshot(testResult.getName().concat(".png"));
            }
        }
    }
```

**Steps to Reproduce**
- Added dependencies as explained here: https://github.com/reportportal/agent-java-testNG#dependencies. 
- Tried adding listener is xml as well as using @Listeners annotation, but still getting error

**Expected behavior**
do not expect errors and logs should be forwarded to reportportal.

**Actual behavior**
Test suite fails to run with error Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener

**Dependency versions**
```xml
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.5</version>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>5.1.2</version>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>5.1.4</version>
            <!--<exclusions> 
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>-->

            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-api</artifactId>
                <version>2.17.2</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-core</artifactId>
                <version>2.17.2</version>
            </dependency>
```

**Additional context**
jvmRun.dump

```
org.testng.TestNGException: 
Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener
	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:41)
	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:59)
	at org.testng.ITestObjectFactory.newInstance(ITestObjectFactory.java:10)
	at org.testng.internal.objects.SimpleObjectDispenser.dispense(SimpleObjectDispenser.java:60)
	at org.testng.internal.objects.GuiceBasedObjectDispenser.dispense(GuiceBasedObjectDispenser.java:28)
	at org.testng.TestNG.addListeners(TestNG.java:993)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:950)
	at org.testng.TestNG.initializeEverything(TestNG.java:1041)
	at org.testng.TestNG.run(TestNG.java:1052)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:38)
	... 15 more
Caused by: java.lang.NoSuchMethodError: 'okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.callTimeout(java.time.Duration)'
	at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:542)
	at com.epam.reportportal.service.ReportPortal$Builder.lambda$buildClient$1(ReportPortal.java:430)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:430)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:407)
	at com.epam.reportportal.testng.TestNGService.<clinit>(TestNGService.java:93)
	at com.epam.reportportal.utils.MemoizingSupplier.get(MemoizingSupplier.java:42)
	at com.epam.reportportal.testng.ReportPortalTestNGListener.<init>(ReportPortalTestNGListener.java:33)
	... 21 more
```

For additional context, the log4j2.xml is setup as below

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration packages="com.epam.ta.reportportal.log4j.appender" monitorInterval="5">
    <properties>
        <property name="reportportalpattern">[%d{HH:mm:ss}] %-5p (%F:%L) - %m%n%throwable</property>
    </properties>
    <Appenders>
        <Console name="ConsoleAppender" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t-%M] %-5level %logger{36} - %msg%n%throwable" />
        </Console>
        <ReportPortalLog4j2Appender name="ReportPortalAppender">
            <PatternLayout
                    pattern="${reportportalpattern}"/>
        </ReportPortalLog4j2Appender>
    </Appenders>
    <Loggers>
        <Logger name="com.company.project" level="DEBUG">
            <AppenderRef ref="ConsoleAppender"/>
        </Logger>
        <Root level="ALL">
            <AppenderRef ref="ReportPortalAppender"/>
        </Root>
        <Logger name="com.epam.reportportal" level="WARN" additivity="false">
            <AppenderRef ref="ConsoleAppender"/>
        </Logger>
        <!--<Logger name="binary_data_logger" level="DEBUG" additivity="false">
            <AppenderRef ref="ReportPortalAppender"/>
        </Logger>-->
    </Loggers>
</Configuration>
```

Also, adding the config file (reportportal.properties), in case it helps

```
rp.endpoint = https://reportportal.xxx.xxx.com
rp.uuid = <some-uuid>
rp.launch = <some-launch-name>
rp.project = <project-name>
rp.description = <description>
rp.attributes = key:value
rp.skipped.issue = false
rp.enable = false
```
`rp.enable` is set to true explicitly in mvn targets or commands. For e.g. - `mvn clean test -DsuiteXmlFile=testng.xml -Denv=QA -Drp.enable=true`

**Comment by HardNorth** [comment]
The real problem in this line: `java.lang.NoSuchMethodError: 'okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.callTimeout(java.time.Duration)'`. This means `OkHttpClient` class does not have `Builder.callTimeout(java.time.Duration)` method. This happens when your code overrides our dependencies with older versions, which does not contains certain code yet. Most likely you are using old version of Selenium, which also has `OkHttpClient` dependency. Please update it to the latest version on your issue should gone.
