### ISSUE TITLE
org.testng.TestNGException:  Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener

### ISSUE THREAD

**Issue by HarishHebbar1** [reportportal/examples-java#62]
Unable run testng.xml file for Report portal and tests not reporting to report portal.
I am wanted to execute selenium tests and create report portal test report. I am using java maven TestNG framework.
The allure reporting is working fine for me and I wanted to add report portal to same project. Kindly assist.
 POM:
<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-testng</artifactId>
			<version>5.1.2</version>
		</dependency>
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>client-java</artifactId>
			<version>5.1.11</version>
		</dependency>
		<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>logger-java-log4j</artifactId>
			<version>5.1.4</version>
			<exclusions>
				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.36</version>
		</dependency>

		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-slf4j-impl</artifactId>
			<version>2.17.2</version>
		</dependency>
<build>

		
		
		

		
		
			<plugins>

				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<configuration>
						<source>8</source>
						<target>8</target>
					</configuration>
				</plugin>

				
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>${MavenSurefire.version}</version>
					
					<configuration>
						<forkCount>0</forkCount>
						<argLine>-Xmx1024m -XX:MaxPermSize=256m</argLine>
						<suiteXmlFiles>

							
							<suiteXmlFile>${testNG.suiteLocation}/${suiteXmlFile}.xml</suiteXmlFile>

						</suiteXmlFiles>

						

						<argLine>
							-javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
						</argLine>
						

						<properties>
							<property>
								<name>usedefaultlisteners</name>
								<value>false</value>
							</property>
						</properties>
					</configuration>

					<dependencies>

						
						

							<dependency>
								<groupId>org.aspectj</groupId>
								<artifactId>aspectjweaver</artifactId>
								<version>${aspectj.version}</version>
							</dependency>

						</dependencies>

				</plugin>

				<plugin>
					<groupId>io.qameta.allure</groupId>
					<artifactId>allure-maven</artifactId>
					<version>2.10.0</version>
					<configuration>
						<propertiesFilePath>resources/allure.properties</propertiesFilePath>
					</configuration>
				</plugin>				

			</plugins>

			

            </build>

org.testng.TestNGException: 
Cannot instantiate class com.epam.reportportal.testng.ReportPortalTestNGListener
	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:41)
	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:59)
	at org.testng.ITestObjectFactory.newInstance(ITestObjectFactory.java:10)
	at org.testng.internal.objects.SimpleObjectDispenser.dispense(SimpleObjectDispenser.java:60)
	at org.testng.internal.objects.GuiceBasedObjectDispenser.dispense(GuiceBasedObjectDispenser.java:28)
	at org.testng.TestNG.addListeners(TestNG.java:993)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:950)
	at org.testng.TestNG.initializeEverything(TestNG.java:1041)
	at org.testng.TestNG.run(TestNG.java:1052)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:38)
	... 10 more
Caused by: java.lang.NoSuchMethodError: 'okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.callTimeout(java.time.Duration)'
	at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:549)
	at com.epam.reportportal.service.ReportPortal$Builder.lambda$buildClient$1(ReportPortal.java:437)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:437)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:414)
	at com.epam.reportportal.testng.TestNGService.<clinit>(TestNGService.java:93)
	at com.epam.reportportal.utils.MemoizingSupplier.get(MemoizingSupplier.java:42)
	at com.epam.reportportal.testng.ReportPortalTestNGListener.<init>(ReportPortalTestNGListener.java:33)
	... 15 more

![image](https://user-images.githubusercontent.com/110990245/183926886-a6c4a661-86c2-4c6c-b074-c7aff7a1b3a7.png)

**Comment by HarishHebbar1** [comment]
Hi team, please help me for above issue.

**Comment by HardNorth** [comment]
Duplicates #61
